language: ruby
rvm:
  - 2.6
  - 2.5
  - 2.4
  - 2.3
  - 2.2
  - jruby-19mode
  - rbx-19mode
services:
  - redis-server
notifications:
  email:
    recipients:
      - andrew@codetree.com
env:
  travis: 'yes'
matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: rbx-19mode
